# Generated by Django 4.2.7 on 2023-11-20 16:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('purse_finance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaidTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=5, max_digits=100)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('merchant_name', models.CharField(default=None, max_length=255, null=True)),
                ('is_pending', models.BooleanField(default=True)),
                ('category_id', models.CharField(blank=True, default='', max_length=255)),
                ('transaction_id', models.CharField(max_length=255, unique=True)),
                ('date_retrieved', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_reviewd', models.BooleanField(default=False)),
                ('plaid_account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='purse_finance.plaidaccount')),
            ],
        ),
    ]
