# Generated by Django 4.2.1 on 2023-12-11 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purse_catalog', '0002_plaidtransactionsubcategory_plaidtransactioncategory'),
        ('purse_finance', '0002_plaidtransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plaidtransaction',
            name='category_id',
        ),
        migrations.AddField(
            model_name='plaidtransaction',
            name='category',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='purse_catalog.plaidtransactioncategory'),
        ),
    ]
